### ISSUE TITLE
widget package is broken

### ISSUE THREAD

**Issue by fschlz** [MicrosoftLearning/mslearn-dp100#100]
It appears that there is no `log_files()` function.

Screenshot from Notebook 5: train models

<img width="1220" alt="image" src="https://user-images.githubusercontent.com/22344801/208671834-a51674ad-39f2-4e6a-b6c5-50059a7c93c8.png">

**Comment by madiepev** [comment]
I'm closing this issue to consolidate it with another issue: https://github.com/MicrosoftLearning/mslearn-dp100/issues/107 we're aware of the issue with this lab and actively investigating it. Any updates will be posted under the other issue.
