### ISSUE TITLE
Error in libraries/packages notebook 15

### ISSUE THREAD

**Issue by AdolfoG22** [MicrosoftLearning/mslearn-dp100#101]
Running the Notebook 15 today in class we got several errors. Attached the executed Notebook.

[15 - Detect Unfairness.pdf](https://github.com/MicrosoftLearning/mslearn-dp100/files/10280839/15.-.Detect.Unfairness.pdf)

Thank you

**Comment by madiepev** [comment]
Install of raiwidgets is set to a specific version to avoid this issue. Thanks for reporting it!
