### ISSUE TITLE
LAB: Use Automated Machine Learning scripts broken

### ISSUE THREAD

**Issue by chris-utter** [MicrosoftLearning/mslearn-dp100#105]
Lab: Use Automated Machine Learning
Section: Provision an Azure Machine Learning workspace
Sub: Create the workspace
Step: 5

bash command line not formatted properly, reads as ```bash rm -r mslearn-dp100 -f git clone https://github.com/MicrosoftLearning/mslearn-dp100 mslearn-dp100.  Correct should be a type-text box without '''bash

setup.sh script fails either creating workspace or compute

**Comment by GraemeMalcolm** [comment]
Actually, the problem isn't the "bash" language signifier - it's that the code fence isn't closed - you need ``` and black line after the code block.

**Comment by chris-utter** [comment]
Thanks Graeme! I was unable to create the workspace manually, so I checked and the Microsoft.MachineLearning resource provider was not registered either. Registering to see if that clears the issue.

Chris Utter
Worldwide Learning
Microsoft
________________________________

**Comment by chris-utter** [comment]
I was able to successfully create the workspace after registering the resource, but I also logged out and logged back in, so not sure which step solved the issue.

I am working with British Petroleum US today. They are moving away from AML tomDatabricks due to performance issues. The Azure Lass Subscriptions are not providing a favorable view of AML.

Chris Utter
Worldwide Learning
Microsoft
________________________________

**Comment by madiepev** [comment]
Ive fixed the code block. Let me know if there still is an issue!
