### ISSUE TITLE
Module 4- RUN Experiment Code is running in Never Ending Loop

### ISSUE THREAD

**Issue by sehrish777** [MicrosoftLearning/mslearn-dp100#107]
It is taking too much time to complete the experiment, it is more than 5 hours, but the experiment is kept on running.
 The screenshot is attached here.

Was this lab tested ever? Has someone else faced this issue? 
Please advise. 

![image](https://user-images.githubusercontent.com/52242119/215213202-062451cf-d3a1-425e-8874-eea6ca0be0e6.png)

**Comment by fzouari** [comment]
I have the same error not only for module 4 but also other modules whenever there is ScriptRunConfig... I noted that the environment image is not built... 

Those who fixed it, please let us know! Thanks! 

![image](https://user-images.githubusercontent.com/52094125/215322772-d7407007-f870-4e5f-9ec7-9aadbc60f896.png)

**Comment by sehrish777** [comment]
Ahhh @fzouari  Thanks for adding, unfortunately not only 5 hours but it is running constantly beyond 10 hours. 
![image](https://user-images.githubusercontent.com/52242119/215480660-fb8719bd-0c23-4dc5-bda8-f633b41fb5e0.png)

**Comment by madiepev** [comment]
Thanks for reporting this. This lab is continuously tested, and this error hasn't occurred before. However, after replicating your steps I get the same result now so I'll submit a support ticket and investigate what could cause this with the support team. I'll update when I get more news.

**Comment by fzouari** [comment]
@sehrish777 @madiepev 
I managed to get it to run, it was simply by explicitly specifying the compute_target in ScriptRunConfig. 
You can either use the name string of your compute instance from your compute tab in Azure ML studio or you can retrieve it from your workspace instance using the following command `next(iter(ws.compute_targets))`. 

Nevertheless, I would like to understand why the error was occurring... According to the documentation: "If no compute target is specified, your local machine will be used.". What is meant by local machine, here? Is there any set up that needs to be done to make sure the local compute is accessed during the run? 

Thanks in advance!

**Comment by madiepev** [comment]
Support is letting me know there was a bug that has been fixed. I'm still getting another error that seems to be related to the widget. If you delete `RunDetails(run).show()` the notebooks should run without issues. I'm checking with support on this issue too, but for now the workaround is to delete `RunDetails(run).show()` before running a cell.

**Comment by madiepev** [comment]
We're still actively investigating the issue: things you may try to mitigate the issue:
- Remove `RunDetails(run).show()`
- Specify the `compute_target` to be the compute instance name.
- Cancel runs stuck in starting. Restart your compute instance and try again.

**Comment by madiepev** [comment]
There is a bug with new compute instances that is causing some issues. To avoid waiting on the issue to be resolved, the lab now checks for and creates a compute cluster which is used as the compute target.
