### ISSUE TITLE
Errors in Notebook 13

### ISSUE THREAD

**Issue by AdolfoG22** [MicrosoftLearning/mslearn-dp100#110]
I attach pdf of notebook executed and the errors that are generated.

[13 - Explore Differential Privacy compress.pdf](https://github.com/MicrosoftLearning/mslearn-dp100/files/10560662/13.-.Explore.Differential.Privacy.compress.pdf)

**Comment by madiepev** [comment]
Thanks for reporting this. There is currently an issue with the compute instance which is making it hard to troubleshoot the error. When that issue is resolved, we'll try to fix this too.

**Comment by tylerfarmer1** [comment]
FYI, I ran it today, and everything seemed to work...however, there are only 6 code blocks now, there used to be 11 of them.   All the blocks that run SQL queries are no longer there.

**Comment by madiepev** [comment]
The SQL queries have been removed as they're deprecated in the SDK and resulted in errors. This course will be updated to v2 soon.
