### ISSUE TITLE
Lab 4, missing python module azureml-sdk

### ISSUE THREAD

**Issue by tylerfarmer1** [MicrosoftLearning/mslearn-dp100#114]
In this file:
https://github.com/MicrosoftLearning/mslearn-dp100/blob/main/instructions/04-run-experiments.md

There is a section that says "Verity the Azure Machine Learning SDK is installed" and the user types 

> pip show azureml-sdk

The instructions say "Note the version of the SDK Package installed."   However, it isn't installed...

User need to run:

> pip install azureml-sdk

and then re-run "pip show" and all should be well. 

HOWEVER - I don't think that module is even necessary for Lab 4...everything seems to work find without it.

**Comment by madiepev** [comment]
Thanks for reporting. I see the compute instances have been updated to I changed the instructions to install them.
