### ISSUE TITLE
Lab 4, missing python module azureml-mlflow

### ISSUE THREAD

**Issue by tylerfarmer1** [MicrosoftLearning/mslearn-dp100#115]
This is in the Notebook file:

https://github.com/MicrosoftLearning/mslearn-dp100/blob/main/04%20-%20Run%20Experiments.ipynb

There are 2 issues here.   One is with "azureml-mlflow" and the other is with just "mlflow."

Code Block 14 say to execute:
`pip show azureml-mlflow`
And it is expecting it to be installed, but it isn't installed. You see this:
`WARNING: Package(s) not found: azureml-mlflow`

Follow on ERROR:   During the `pip install azureml-mlflow` process, an error is shown on the screen.   I don't think it's a show stopper, because the rest of the lab seems to run.   The error is:

```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
azureml-widgets 1.48.0 requires jinja2<=2.11.2, but you have jinja2 3.0.3 which is incompatible.
```
'

Code Block 15 doesn't work initially.   However, once you install azureml-mlflow, then Block #15 works...  But it's odd that code block 15 only reference "mlflow" and not "azureml-mlflow" because of the 3rd line that says:
`import mlflow`

Summary:  Once you run 
`pip install azureml-mlflow`
the rest of the code blocks seem to work.

**Comment by madiepev** [comment]
Fixed it to install
