### ISSUE TITLE
Lab 9, errors with joblib and sklearn

### ISSUE THREAD

**Issue by tylerfarmer1** [MicrosoftLearning/mslearn-dp100#116]
This is in the file:

https://github.com/MicrosoftLearning/mslearn-dp100/blob/main/09%20-%20Create%20a%20Real-time%20Inferencing%20Service.ipynb

In Code Block 2, the line
`import joblib`
fails with code
`moduleNotFoundError: No module named 'joblib'`

I ran:
`pip install joblib`
which completed successfully.

Then the Code Block fails on the line
`from sklearn.model_selection import train_test_split`
It fales with the message:
`ModuleNotFoundError: No module named 'sklearn'`

I ran:
`pip install sklearn`
which completed successfully.

However, the Code Block still fails with the same error, saying sklearn isn't found.  

There is something very odd though...   The Code Block 2 from Lab 10 is the same code, and it works just fine...  So I'm not sure what's happening with the Lab 9 file.

**Comment by madiepev** [comment]
fixed
