### ISSUE TITLE
Lab 11, missing azureml-train-automl

### ISSUE THREAD

**Issue by tylerfarmer1** [MicrosoftLearning/mslearn-dp100#117]
Lab 11, This is in the file:

https://github.com/MicrosoftLearning/mslearn-dp100/blob/main/12%20-%20Use%20Automated%20Machine%20Learning.ipynb

Code Block 1 says
`pip show azureml-train-automl`
and you get a warning:
`WARNING: Package(s) not found: azureml-train-automl`

I ran:
`pip install azureml-train-automl`
which installs, but give an ERROR during installation:

```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
googleapis-common-protos 1.58.0 requires protobuf!=3.20.0,!=3.20.1,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.19.5, but you have protobuf 3.20.1 which is incompatible.
google-api-core 2.11.0 requires protobuf!=3.20.0,!=3.20.1,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.19.5, but you have protobuf 3.20.1 which is incompatible.

```

Anyway, even though the install of `azureml-train-automl` gives the error, the Code Block 1 in the Notebook completes successfully.

**Comment by madiepev** [comment]
I'm changing the kernel to 3.8 Azure ML to avoid these issues. For any future issues, try it with that kernel if you don't clone the updated repo.
