### ISSUE TITLE
Lab 15 errors

### ISSUE THREAD

**Issue by tylerfarmer1** [MicrosoftLearning/mslearn-dp100#118]
Lab 15, this is file:
https://github.com/MicrosoftLearning/mslearn-dp100/blob/main/15%20-%20Detect%20Unfairness.ipynb

Code block 1 checks for azureml-contrib-fairness, but it isn't installed.   Need to just add a "pip install" for that.

Then in Code Block 5 the line:
`from raiwidgets import FairnessDashboard`
generates an error:
`ImportError: cannot import name 'soft_unicode' from 'markupsafe' (/anaconda/envs/jupyter_env/lib/python3.8/site-packages/markupsafe/__init__.py)`

**Comment by madiepev** [comment]
fixed
