### ISSUE TITLE
Kernel not available / takes long time to load

### ISSUE THREAD

**Issue by pjongbloed** [MicrosoftLearning/mslearn-dp100#119]
I've been getting the following error, yesterday & today:

![image](https://user-images.githubusercontent.com/81766286/218259115-826547d0-8d2e-4c1a-b24b-c2ccb3b8202b.png)

Only after leaving the compute running for a long time and trying various other things, eventually it came up.
So for some reason, it seems it's just very slow in loading at the moment?

**Comment by tylerfarmer1** [comment]
I'm teaching the class on Monday, so I went through all the labs today, and didn't have this problem at all.

**Comment by madiepev** [comment]
Thanks for raising this. If this problem persists I'd recommend submitting a support ticket as this is a problem with the product, not with the learning content.
