### ISSUE TITLE
Lab 2 and 3 - Missing Instructions for cloning the notebooks

### ISSUE THREAD

**Issue by tylerfarmer1** [MicrosoftLearning/mslearn-dp100#120]
This is for the file called:

https://github.com/MicrosoftLearning/mslearn-dp100/blob/main/instructions/02-automated-ml.md
and
https://github.com/MicrosoftLearning/mslearn-dp100/blob/main/instructions/03-azureml-designer.md

Both files have a section towards the bottom of the page to Test the Endpoint.   It tells you to open the correct Notebook and do the testing; however, it is missing instructions to actually clone the notebook first.

Lab 1 has the instructions, but you that gets deleted before you start Lab 2 or Lab 3.      Lab 4 (and I believe the rest) include the instructions for cloning the Notebooks.    I think we should do that in Lab 2, and then don't delete anything, and the rest of the labs will already have everything cloned correctly.

**Comment by madiepev** [comment]
Thank you. Updated instructions.
