### ISSUE TITLE
Error in Lab 12

### ISSUE THREAD

**Issue by tylerfarmer1** [MicrosoftLearning/mslearn-dp100#121]
This is for the Jupyter Notebook in Lab 12.

In Code Block 12, the first line is:
`best_run, fitted_model = automl_run.get_output()`

But it throws an error:

`PermissionError: [Errno 1] Operation not permitted: '/anaconda/envs/azureml_py38/lib/python3.8/site-packages/nimbusml/internal/libs/pybridge.so'
`

**Comment by madiepev** [comment]
Thanks for reporting this. Looks like a bug in the product. I'm able to reproduce the error so I'm checking with support to see what the cause can be. I'll update when I know more.

**Comment by tylerfarmer1** [comment]
How can I send a private message / comment to you?

**Comment by madiepev** [comment]
You can email me by adding @microsoft.com to my alias. FYI I'll delete this comment after you've seen it.

**Comment by madiepev** [comment]
this issue should be resolved now! you may have to create a new compute instance to see the fix

**Comment by VEshelbyMTT** [comment]
Experienced this issue today in one of my classes - the temporary fix you provided worked but just want you to be aware that the problem isn't over! :(
