### ISSUE TITLE
Lab 15, missing module

### ISSUE THREAD

**Issue by tylerfarmer1** [MicrosoftLearning/mslearn-dp100#122]
This is in the Jupyter Notebook for Lab 15

The first code block is:
`pip show azureml-contrib-fairness`

However, it isn't installed....  My suggestion is change it to:
`pip install azureml-contrib-fairness`

**Comment by madiepev** [comment]
Thanks for reporting this. The kernel should be set to Python 3.8 Azure ML. Then the package should already be installed and you don't need to run pip install. The default kernel of the notebook should be set to this too. Let me know if the problem persists.
