### ISSUE TITLE
Package conflict warning message resulting in error

### ISSUE THREAD

**Issue by CamronBorealis** [MicrosoftLearning/mslearn-dp100#13]
I've been doing several of the workbooks, and often, when I submit an experiment, I have been getting the message:

> Expected a StepRun object but received <class 'azureml.core.run.Run'> instead.
> This usually indicates a package conflict with one of the dependencies of azureml-core or azureml-pipeline-core.
> Please check for package conflicts in your python environment

And today, when I went to complete workbook "10 - Create a Batch Inferencing Service.ipynb", I was running the cell right after the text "When the pipeline has finished running, the resulting predictions will" (there is only one instance of this text in the workbook) when I got this error:

> AttributeError                            Traceback (most recent call last)
> <ipython-input-11-8abc90127c6c> in <module>
>       7 # Get the run for the first step and download its output
>       8 prediction_run = next(pipeline_run.get_children())
> ----> 9 prediction_output = prediction_run.get_output_data('inferences')
>      10 prediction_output.download(local_path='diabetes-results')
>      11 

AttributeError: 'Run' object has no attribute 'get_output_data'

Looking at the docs, it would seem that line 9 is expecting a StepRun object, not a Run object.

**Comment by GraemeMalcolm** [comment]
So the package conflict warning should be mitigated since we now just use whatever version of the SDK is installed on a new CI by default.
The issue you're seeing in lab 10 is actually just because it takes a few seconds for the results to become available. So for example, if you just run the notebook, you'll get the error you describe; but if you run each cell individually (or just everythong up to the point where the pipeline is run; and then wait a few seconds before retrieving the results), it works as-is.

**Comment by DieselAnalytics** [comment]
I know this is closed but I am having the same issue. I did as you said, I ran the code up to the cell in question and then ran the cell and got the same error as @CamronBorealis. I tried to split the cell that was causing the problem and that did not solve it. See below:  

<img width="450" alt="image" src="https://user-images.githubusercontent.com/16294340/178116621-7a05ca7c-22c3-4512-b1a2-0d9ed6bc4de2.png">

**Comment by DieselAnalytics** [comment]
This looks like an error in the code because I looked at the docs and I did not see that as a method of the Run class:  https://docs.microsoft.com/en-us/python/api/azureml-core/azureml.core.run(class)?view=azure-ml-py

**Comment by DieselAnalytics** [comment]
Hello @madiepev,

It appeared to finish running. Please see below:

<img width="308" alt="image" src="https://user-images.githubusercontent.com/16294340/178553942-e5dcf513-f500-454c-a82a-002f11668a99.png">

**Comment by madiepev** [comment]
@DieselAnalytics could you check the Azure ML SDK version you're using (should be visible after running the first cell). And have you tried running everything once again?

**Comment by DieselAnalytics** [comment]
I updated the Azure ML SDK and it is now working. Thanks @madiepev!
