### ISSUE TITLE
Missing "pip install --upgrade azureml-sdk[notebooks,automl,explain] --verbose"->Model-Deploymenterror.

### ISSUE THREAD

**Issue by GitHub-Soliman** [MicrosoftLearning/mslearn-dp100#16]
Moin Moin.
Upon trying to deploy the best model as the endpoint "auto-predict-diabetes" from "https://microsoftlearning.github.io/mslearn-dp100/instructions/02-automated-ml.html", I did receive an error.:
_________________________________________________________________
Failed to load entrypoint automl = azureml.train.automl.run˸AutoMLRun._from_run_dto with exception (cryptography
_________________________________________________________________
issuing "pip install --upgrade azureml-sdk[notebooks,automl,explain] --verbose" dis remove it.
_Tschüß,
__Michael.

**Comment by GraemeMalcolm** [comment]
The latest version of the lab notebook doesn't include any steps to deploy
