### ISSUE TITLE
typo - cell 16 - 08 - Create a Pipeline.ipynb

### ISSUE THREAD

**Issue by CaioCavalcanti** [MicrosoftLearning/mslearn-dp100#17]
There's a typo on cell 16 of [08 - Create a Pipeline.ipynb](https://github.com/MicrosoftLearning/mslearn-dp100/blob/main/08%20-%20Create%20a%20Pipeline.ipynb).

_First you need to define the steps for the pipeline, and any data references that need **to passed** between them [...]_

Should be:
_First you need to define the steps for the pipeline, and any data references that need **to be passed** between them [...]_

**Comment by GraemeMalcolm** [comment]
Thanks - fixed!
