### ISSUE TITLE
Move instructions into notebooks

### ISSUE THREAD

**Issue by grantcarthew** [MicrosoftLearning/mslearn-dp100#18]
Hi @GraemeMalcolm,

Could we move the instruction markdown information into the Jupyter notebooks?

I know the first lab creates the compute instance which is where Jupyter is launched from. This information could be on the Readme page as a first step or course setup. Once the students finish that part of the labs, they could then focus on the notebooks and not have to jump between two sources of information.

The instructor is always there to help in the mornings to get the students to start the instance.

**Comment by GraemeMalcolm** [comment]
Unfortunately, there are some modalities we need to support where the MD file is required to bootstrap each lab (specifically, hosted lab environments. We also need to assume each lab can be completed standalone as self-paced on Learn (which means we can't assume everyone has completed the previous labs - esp. lab 1)
