### ISSUE TITLE
Global Importance not in default view

### ISSUE THREAD

**Issue by madiepev** [MicrosoftLearning/mslearn-dp100#21]
In "Use Automated Machine Learning", 
under "Review best model", point 5: Select the Explanations tab, and view the Global Importance chart. This shows the extent to which each feature in the dataset influences the label prediction.

Global Importance isn't in default view. Students have to either toggle on "View previous dashboard experience" or look at the new view so then Global Importance should be replaced by "Aggregate feature importance"

**Comment by GraemeMalcolm** [comment]
Fixed - thanks!
