### ISSUE TITLE
04 Run Experiments Doesn't Complete.

### ISSUE THREAD

**Issue by mtowse** [MicrosoftLearning/mslearn-dp100#22]
I have run 04 - Run Experiments.ipynb multiple times now in many new AMLS's and have never managed to get past cell 9 "The following cell configures and submits the script-based experiment.".  The run hangs in "Preparing" with continuous repeated warnings around "Warning: you have pip-installed dependencies in your environment file, but you do not list pip itself as one of your conda dependencies.  Conda may not use the correct pip to install your packages, and they may end up in the wrong place.  Please add an explicit pip dependency.  I'm adding one for you, but still nagging you.".  The https://<sa>.blob.core.windows.net/azureml/ExperimentRun/dcid.mslearn-diabetes_1620313789_c6321d70/azureml-logs/60_control_log.txt file reaches over 300MB.

**Comment by GraemeMalcolm** [comment]
The message you're getting is a warning, which shouldn't block the experiment environment being built. I can't repro the issue (the experiment takes several minutes to build the environment and run, but it does eventually run; which is expected behavior).

Can you share the log file (or at least the last bit iof it so we can see any errors logged there)

**Comment by mtowse** [comment]
I think the size of the log file might be an issue.  It has been "preparing" now for 20 minutes and the log file is 465MB with 1.49 million rows of "Warning: you have pip-installed dependencies in your environment file, but you do not list pip itself as one of your conda dependencies.  Conda may not use the correct pip to install your packages, and they may end up in the wrong place.  Please add an explicit pip dependency.  I'm adding one for you, but still nagging you.".

**Comment by GraemeMalcolm** [comment]
Yeah, it looks like something is broken in the SDK. I'll et back when I have a resolution.

**Comment by GraemeMalcolm** [comment]
OK, as a workaround, modify the cell that submits the experiment as follows (I'm updating the files in the repo as soon as I complete an end-to-end test):

```
from azureml.core import Experiment, ScriptRunConfig, Environment
from azureml.core.conda_dependencies import CondaDependencies
from azureml.widgets import RunDetails

# Create a Python environment for the experiment
env = Environment("experiment_env")

# Ensure the required packages are installed (we need scikit-learn and Azure ML defaults)
packages = CondaDependencies.create(conda_packages=['pip'],
                                    pip_packages=['azureml-defaults'])
env.python.conda_dependencies = packages



# Create a script config
script_config = ScriptRunConfig(source_directory=experiment_folder,
                                script='diabetes_experiment.py',
                                environment=env) 

# submit the experiment
experiment = Experiment(workspace=ws, name='mslearn-diabetes')
run = experiment.submit(config=script_config)
RunDetails(run).show()
run.wait_for_completion()
```

**Comment by GraemeMalcolm** [comment]
New notebooks have been uploaded so that pip is explicitly installed as a Conda dependency. That should resolve the issue.
