### ISSUE TITLE
Receive error GraphDatasetNotFound: Request failed with status code 400 when submitting pipeline

### ISSUE THREAD

**Issue by Hollyazurespain** [MicrosoftLearning/mslearn-dp100#24]
Solution: clicked the first element of the pipeline (dataset) and then just change to another value. And run.

https://docs.microsoft.com/en-us/answers/questions/379678/receive-error-graphdatasetnotfound-request-failed.html

**Comment by GraemeMalcolm** [comment]
Thanks @Hollyazurespain 
I added a tip to the instructions!
