### ISSUE TITLE
04 Run Experiments Still Doesn't Complete.

### ISSUE THREAD

**Issue by nugysemail** [MicrosoftLearning/mslearn-dp100#28]
WARNING:root:The conda environment is currently locked by another AzureML job. Further job submission will wait until the other process finishes. If there are no other jobs running, please delete /home/azureuser/.azureml/locks/azureml_conda_lock

LOG : 
Waiting for other Conda operations to finish...
Delete /home/azureuser/.azureml/locks/azureml_conda_lock to override.

Status : 
Preparing

![4 Experiment](https://user-images.githubusercontent.com/2998731/118650932-2f266e00-b80f-11eb-80d9-5a5e72f039d9.png)

**Comment by GraemeMalcolm** [comment]
Looks like you have a previously running kernel still running.:
1. Sope and close all notebooks
2. Open a terminal and use the `Delete /home/azureuser/.azureml/locks/azureml_conda_lock` command to delete it.
3. Re-open the notebook and run it again.
