### ISSUE TITLE
issue with 13 - Explore Differential Privacy.ipynb

### ISSUE THREAD

**Issue by AroraMunish** [MicrosoftLearning/mslearn-dp100#32]
When running the command !pip install opendp-smartnoise==0.1.3.1, it shows the following error 

ERROR: azure-cli 2.23.0 has requirement antlr4-python3-runtime~=4.7.2, but you'll have antlr4-python3-runtime 4.8 which is incompatible.
ERROR: azure-cli 2.23.0 has requirement azure-graphrbac~=0.60.0, but you'll have azure-graphrbac 0.61.1 which is incompatible.
ERROR: azure-cli 2.23.0 has requirement azure-mgmt-containerregistry==3.0.0rc17, but you'll have azure-mgmt-containerregistry 2.8.0 which is incompatible.
ERROR: azure-cli 2.23.0 has requirement azure-mgmt-keyvault==9.0.0, but you'll have azure-mgmt-keyvault 2.2.0 which is incompatible.
ERROR: azure-cli 2.23.0 has requirement azure-mgmt-network~=18.0.0, but you'll have azure-mgmt-network 19.0.0 which is incompatible.

ERROR: azure-cli 2.23.0 has requirement azure-mgmt-storage~=17.1.0, but you'll have azure-mgmt-storage 11.2.0 which is incompatible.
ERROR: azure-cli 2.23.0 has requirement pytz==2019.1, but you'll have pytz 2021.1 which is incompatible.
ERROR: azure-cli 2.23.0 has requirement websocket-client~=0.56.0, but you'll have websocket-client 0.59.0 which is incompatible.
as attached. 
<img width="805" alt="UnableToInstallSmartNoise" src="https://user-images.githubusercontent.com/13214220/119950209-435d2e80-bfb8-11eb-99c4-196363889178.PNG">

Can anyone please suggest?

**Comment by AroraMunish** [comment]
At one place I found to run the script
`!pip install --upgrade setuptools` before running `!pip install opendp-smartnoise==0.1.3.1`, and it worked..

**Comment by GraemeMalcolm** [comment]
Thanks for sharing this. The "errors" can actually be safely ignored in this case.

**Comment by AroraMunish** [comment]
But shouldn't the script be updated to include `!pip install --upgrade setuptools` , as the next ones can not be run unless the one above is executed?

**Comment by GraemeMalcolm** [comment]
The rest of the notebook runs OK for me without that package.
