### ISSUE TITLE
Application Insights requests are failing from notebooks

### ISSUE THREAD

**Issue by Jason-M-Richards** [MicrosoftLearning/mslearn-dp100#33]
The last couple of classes I have delivered, the app insights requests are going through to the service, but are failing at the server level due to "missing swagger" error. Not sure what this means, but included a screenshot of what I am seeing. There are no outputs to review due to the request fails.

![image](https://user-images.githubusercontent.com/46732841/122300294-bfb2a580-cec4-11eb-9767-bf4c0593fe2a.png)

**Comment by GraemeMalcolm** [comment]
Thanks for reporting this @Jason-M-Richards 
I can confirm that I can replicate the issue. However, if I then return to the notebook and re-run the cell calling the web service, and go back to the Application Insights query and re-run it, I get the expected results.

Looks like something flaky somewhere, but I can't determine exactly where. I've updated the notebook to include a hint to go back and re-run both the web service request and App Insights query. My hope is that even though you might get the failure you've reported, if you go through the cycle enough times it eventually starts working!

**Comment by Jason-M-Richards** [comment]
I appreciate you looking into this and addressing it so quickly.

 

Jason Richards
