### ISSUE TITLE
Change in PipelineData object to OutputFileDatasetConfig

### ISSUE THREAD

**Issue by Jason-M-Richards** [MicrosoftLearning/mslearn-dp100#36]
I am instructor for this course and noticed the change from the PipelineData object. Since this specific object is identified in the slidedeck:

Will we need to update the slidedeck to reference the new object or will will the exam still reference the PipelineData object?

If it still references the PipelineData object, why was this change made?

Thanks, this information will help me with future instruction.

**Comment by GraemeMalcolm** [comment]
This was addressed in last month's updates to the course materials - make sure you've downloaded the latest slides from the DLC.
