### ISSUE TITLE
09: Real time inferencing service -> WebServiceException during service deployment

### ISSUE THREAD

**Issue by andreaskopp** [MicrosoftLearning/mslearn-dp100#37]
Here is a snippet from the error message:
2021-08-06 11:20:02+00:00 Checking the status of deployment diabetes-service.
Failed
Service deployment polling reached non-successful terminal state, current service state: Failed
Operation ID: 48957716-297f-493a-b83a-f006a20c7471
More information can be found using '.get_logs()'
Error:
{
  "code": "AciDeploymentFailed",
  "statusCode": 400,
  "message": "Aci Deployment failed with exception: Error in entry script, ModuleNotFoundError: No module named 'azureml.api'

**Comment by GraemeMalcolm** [comment]
Thanks @andreaskopp .
We're seeing a number of weird issues with deployment today. We're investigating and will update here as soon as we figure out what's going on.

**Comment by GraemeMalcolm** [comment]
Hmm, so it looks like there's been a change in the service that means we need to explicitly include the [azure-ml-api-sdk](https://pypi.org/project/azure-ml-api-sdk/)  package in the web service container image. This seems pretty odd, as that package was last updated in May 2017; but including it in the .yml file for the service configuration seems to resolve the issue.

I've updated the notebooks to reflect this, and I'll investigate further.

**Comment by andreaskopp** [comment]
Thank you for your quick response, Graeme!
BTW - there is a lot of great content in the lessons!

**Comment by agarfau** [comment]
Hi!
FYIO, explicitly including the package [azureml-model-management-sdk](https://pypi.org/project/azureml-model-management-sdk/) also solves the issue. Please, if possible, keep this issue updated with any info on this from Microsoft's side. I had to manually go into old running ACI webservice container and compare its `pip list` with a that of a new webservice that was failing with the aforementioned error. The `azureml-model-management-sdk` package was the only `azure*` difference.

**Comment by GraemeMalcolm** [comment]
Thanks for the additional info - interesting!
I'm working with the Azure ML product team on this, and it should be addressed in a future update. I'll post here when it's fully resolved.

**Comment by rradhakr-git** [comment]
Hello - 

I got this issue"<no module named azureml.api.>" couple of days back when I tried to deploy a variation of a currently running in production model  As per the suggestion, i included the <azure-ml-api-sdk> explicitly in my yml file but now I am getting this error 

 _.     **AttributeError: Can't get attribute 'new_block' on <module 'pandas.core.internals.blocks'**_


I tried pandas version - 1.2 / 0.25 but the error stays -

I have a demo scheduled already and I never thought I will get in to this problem as I was trying with a working model

Any help is much appreciated

Thanks

**Comment by rradhakr-git** [comment]
Hello -

I got this issue  **_No module named 'azureml.api_** couple of days back when I tried to deploy a variation of a currently running in production model As per the suggestion, i included the **_azure-ml-api-sdk_** library explicitly in my yml file but now I am getting this error

. AttributeError: Can't get attribute 'new_block' on <module 'pandas.core.internals.blocks'

I tried pandas version - 1.2 / 0.25 but the error stays -

I have a demo scheduled already and I never thought I will get in to this problem as I was trying with a working model

Any help is much appreciated

Thanks

**Comment by madiepev** [comment]
@rradhakr-git are you getting this issue when following the instructions and working with the lab assets? Or does this issue occur when working with your own model (and scripts)?

**Comment by rradhakr-git** [comment]
Sorry - I was aware that this community is for the learning - but saw a comment about a recent change in the core product library and since my problem appear to be affected by the same problem , I asked the question here - Thanks for the response -
