### ISSUE TITLE
fairlearn widget

### ISSUE THREAD

**Issue by raybellwaves** [MicrosoftLearning/mslearn-dp100#4]
When running through

https://github.com/MicrosoftLearning/mslearn-dp100/blob/main/15%20-%20Detect%20Unfairness.ipynb

I ran

```
from fairlearn.widget import FairlearnDashboard

# View this model in Fairlearn's fairness dashboard, and see the disparities which appear:
FairlearnDashboard(sensitive_features=S_test, 
                   sensitive_feature_names=['Age'],
                   y_true=y_test,
                   y_pred={"diabetes_model": diabetes_model.predict(X_test)})
```

the info above suggest that a widget will appear

"Run the cell below (note that a warning about future changes may be displayed - ignore this for now).
When the widget is displayed, use the Get started link to start configuring your visualization."

However, when I run it I just see

```

/anaconda/envs/azureml_py36/lib/python3.6/site-packages/fairlearn/widget/_fairlearn_dashboard.py:47: UserWarning: The FairlearnDashboard will move from Fairlearn to the raiwidgets package after the v0.5.0 release. Instead, Fairlearn will provide some of the existing functionality through matplotlib-based visualizations.
  warn("The FairlearnDashboard will move from Fairlearn to the "
<fairlearn.widget._fairlearn_dashboard.FairlearnDashboard at 0x7f44d83d8e48>
```

<img width="1029" alt="Screen Shot 2020-12-12 at 8 37 55 PM" src="https://user-images.githubusercontent.com/17162724/102000922-599d5980-3cba-11eb-8285-5ec1b2fba9ab.png">

I'm unsure how to see the widget

**Comment by GraemeMalcolm** [comment]
From the screenshot, it looks like you're running this in the notebook page in AML Studio. It will only work in Jupyter (not JupyterLab!)
These limitations are why the Fairlearn folks are planning to change the implementation - as soon as they do, we'll update the notebooks here; but until then you need to run the notebook in Jupyter as instructed.

**Comment by CaioCavalcanti** [comment]
@GraemeMalcolm I'm getting the same error running the notebook in Jupyter

![image](https://user-images.githubusercontent.com/3620566/112056849-d2813c80-8b58-11eb-8163-98f259fd82df.png)

**Comment by GraemeMalcolm** [comment]
The warning is expected.
If the widget is not showing in Jupyter, try restarting the kernel and rerunning

**Comment by CaioCavalcanti** [comment]
restarting the kernel didn't help, but refreshing the page did the trick (found [here](https://github.com/fairlearn/fairlearn/issues/484#issuecomment-759156811)). Thanks!
