### ISSUE TITLE
Outdated answer on "Module 6 - Review Questions"

### ISSUE THREAD

**Issue by FMartull** [MicrosoftLearning/mslearn-dp100#41]
Hello, 

I am taking the ESI Course "DP-100 Designing and Implementing a Data Science Solution on Azure" and on the LabOnDeman module 6 questions, there is an outdated answer (thanks to Oleksiy Nazarenko for spotting it) :

![image](https://user-images.githubusercontent.com/40671906/130814931-237df096-99f0-4635-8c53-14cea08b3178.png)

The OutputFileDatasetConfig object is a special kind of data reference that is used for interim storage locations that can be passed between pipeline steps, so you'll create one and use at as the output for the first step and the input for the second step.

Thank you

**Comment by GraemeMalcolm** [comment]
The lab review questions were added to the lab environment by the hoster, and are not officially part of the content. I've asked them to remove the questions from the lab as they should be completed as a class using the slides provided in the official content.
