### ISSUE TITLE
Issue on Module16 

### ISSUE THREAD

**Issue by sudhakavya** [MicrosoftLearning/mslearn-dp100#44]
**Module** : 16
**Cell** : 05
issue: After running the script to download the score_diabetes.py in Cell 4, facing issue saying that score_diabetes.py doesn't exist in diabetes_service folder.

![Screenshot (14)](https://user-images.githubusercontent.com/69506830/131477433-8ae7a4e1-8535-4681-9032-c99c5e25d076.png)

How to resolve:
 
- Replace the Script_file with Script_path. (score_diabetes.py will be available in the diabetes_service) then it will never show the message saying that doesn't exist and will start Deploying model. 
 
![Screenshot (15)](https://user-images.githubusercontent.com/69506830/131478434-eaf8df26-ad3c-48db-9d7a-2db9fdd20f7f.png)

please make a change in the repo @GraemeMalcolm @Resseguie

**Comment by GraemeMalcolm** [comment]
Not repro for me - @Madiepev, can you take a look?

**Comment by GraemeMalcolm** [comment]
Thanks!

**Comment by madiepev** [comment]
@sudhakavya we updated the notebook!

**Comment by sudhakavya** [comment]
@madiepev @GraemeMalcolm thank you so much for updation of Notebook, Now its working fine
