### ISSUE TITLE
Attribute error when running DP-100 notebook labs

### ISSUE THREAD

**Issue by Kingkij** [MicrosoftLearning/mslearn-dp100#52]
Hi Team,

This may be more of an issue on my side but i am unable to get the notebooks working. 
When I run the mslearn lab 4 and 5 i get the following error.
AttributeError: 'MSIAuthentication' object has no attribute 'get_token'

Apologies if ive missed something.

Thanks

**Comment by GraemeMalcolm** [comment]
I'll close this for now - feel free to post back here if you resolve or continue to have the issue.
