### ISSUE TITLE
Attribute error when running mslearn-dp100 labs

### ISSUE THREAD

**Issue by Kingkij** [MicrosoftLearning/mslearn-dp100#53]
Hi Team 

I'm still getting attribute errors when running the labs. 
In all the labs this occurs whenever i want to connect to my workspace, preventing me from progressing through the rest of the notebook.

Error:
"AttributeError: 'MSIAuthentication' object has no attribute 'get_token'"

![image](https://user-images.githubusercontent.com/63725580/139596065-423eeb7b-b9da-4bd7-b198-048fe424ce87.png)

Im unsure as to why this is happening, do i require an update or is there something i have missed

Thanks

**Comment by Kingkij** [comment]
My apologies, the image was quite blurry hope this is a little bit better. 

[image](https://user-images.githubusercontent.com/63725580/139596331-bb6f9497-ab89-4872-9b35-ebfb94ee3807.png)

**Comment by GraemeMalcolm** [comment]
Looks like you're using the embedded notebook in AML Studio. Do you get the same issue when using Jupiter?

Cheers,
G
___________________________
Graeme Malcolm
Data & AI Content Dev Lead
Worldwide Learning
________________________________

**Comment by GraemeMalcolm** [comment]
Also, if that doesn't work, what happens if you try to connect to the workspace with explicit details instead of a config file - like this?

ws = Workspace.get(name="myworkspace",
               subscription_id='<azure-subscription-id>',
               resource_group='myresourcegroup')

**Comment by madiepev** [comment]
@Kingkij another thing that you can try is `pip install azureml-core --upgrade`
From what I can see you're working in a workspace you also use for other work, could it be that there are any security measures in place? Is a service principal used to authenticate in the workspace? Or is your compute instance in a VNET? In other words, is the compute instance created according to the instructions specified in this repo?

**Comment by Kingkij** [comment]
Cheers guys. 

Yes I am using my azure sentinel AML workspace. Reviewing the steps carefully I realised that i took the same steps as explained in Lab 1 to create a workspace so doubt that is the issue. 

That being said i will have a look and try these solutions out. 

Will update the feed on my progress.

**Comment by GraemeMalcolm** [comment]
If that doesn't work, can you create a new Workspace and try from scratch? The lab instructions here are specific to the course they come from, and we can really only support completing them as-written from end to end. If there's some additional configuration you've done in the workspace you created for Azure Sentinel, that may be what's causing the issue.
