### ISSUE TITLE
Endpoint deployment instructions after the update

### ISSUE THREAD

**Issue by elenamoor** [MicrosoftLearning/mslearn-dp100#54]
https://github.com/MicrosoftLearning/mslearn-dp100/blob/main/instructions/02-automated-ml.md#deploy-a-predictive-service

Deploy a predictive service-> step 2:
Name: auto-predict-diabetes - Endpoint name should be unique to the region and setting up the same name is resulting in BadName error OR just shows no progress to a user and confuses. It also sometimes just retraces users back to step 1 or gives a quota error (if users tried multiple times)

Compute type: ACI - there is no such type in the GUI after the update, please change to Managed 
Enable authentication: Selected - Please change to Key

further instructions are also not reflecting the update change, please check 

If you have any questions, please reach out
Elena Moor

**Comment by madiepev** [comment]
I've updated the instructions. Use the **Deploy to web service** instead of **Deploy to real-time endpoint**.
