### ISSUE TITLE
(Notebook 10) StepRun object not recognised  

### ISSUE THREAD

**Issue by masgra** [MicrosoftLearning/mslearn-dp100#57]
When I run the cell

```python 
import pandas as pd
import shutil

# Remove the local results folder if left over from a previous run
shutil.rmtree('diabetes-results', ignore_errors=True)

# Get the run for the first step and download its output
prediction_run = next(pipeline_run.get_children())
prediction_output = prediction_run.get_output_data('inferences')
prediction_output.download(local_path='diabetes-results')
...
```

I ran into the following issue: 

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
C:\Users\MARTIN~1\AppData\Local\Temp/ipykernel_2100/635567818.py in <module>
      7 # Get the run for the first step and download its output
      8 prediction_run = next(pipeline_run.get_children())
----> 9 prediction_output = prediction_run.get_output_data('inferences')
     10 prediction_output.download(local_path='diabetes-results')
     11 

AttributeError: 'Run' object has no attribute 'get_output_data'
```

I understand that StepRun inherits the Run class, but shouldn't the get_output_data() method be present anyway?

Any suggetion how to overcome this issue?

**Comment by masgra** [comment]
I am using `azureml-sdk Version: 1.37.0` to run the Pipeline

**Comment by madiepev** [comment]
@masgra I reran the notebook and noticed an unnecessary import stopping the cell that defined the Pipeline Steps from fully executing. Could you try it out with the new notebook? Or delete the line: from azureml.core.runconfig import DockerConfiguration

**Comment by masgra** [comment]
> @masgra I reran the notebook and noticed an unnecessary import stopping the cell that defined the Pipeline Steps from fully executing. Could you try it out with the new notebook? Or delete the line: from azureml.core.runconfig import DockerConfiguration

@madiepev thanks for the fast response! I think it`s good that you removed the unnecessary import from the notebook, although this did not solve the issue per se. 

In the meantime, I figured out what caused it, which was an indifference in the packages on my local compute, which was caused by the installation of `ipykenel` later on. 
Do you think it would be benefitial to include local_environment.yaml, just to ensure that everyone uses the same environemnt to run the notebooks?
cheeres

**Comment by madiepev** [comment]
@masgra thanks for closing the issue! 

As per the instructions we're assuming that people are creating a Compute Instance in Azure ML to run the notebooks, which should mean everyone has the same environment when executing the notebooks. 

When you say local compute, do you mean you ran the notebooks locally on your own device?

**Comment by masgra** [comment]
Yes, I run the Notebooks in VS Code. Its the setup I feel most comfortable with, especially combined with the AML extension. 
Usually, I use my device also as a compute target, especialy for engineering tasks, because all the setups runs much faster than on the remote computes. But for this learning path, i use only the recommendet remote compute cluster.

**Comment by madiepev** [comment]
@masgra completely understand your preference for VS Code (same here). However, these labs have been designed to work with the Compute Instance. Using a local device can potentially cause issues as you actually described above as people will have different environments installed. We use these labs to teach classes and to ensure everyone has the same environment without needing to install anything locally, we use the Compute Instance instead of a local VS Code. Hope that makes sense!
