### ISSUE TITLE
ModuleNotFoundError: No module named 'azureml.api'

### ISSUE THREAD

**Issue by ArunP-AtreyaLabs** [MicrosoftLearning/mslearn-dp100#59]
I am trying to deploy models with ACI , 

env.python.conda_dependencies.add_pip_package("azureml-defaults")
env.python.conda_dependencies.add_pip_package("azureml-model-management-sdk")
env.python.conda_dependencies.add_pip_package("azure-ml-api-sdk")

I have installed the dependencies ...

**Comment by madiepev** [comment]
@ArunP-AtreyaLabs could you give me more details? Which lab are you doing? Are you running the notebook on the compute instance created in the workspace? After running which cell do you get this error message?

**Comment by ArunP-AtreyaLabs** [comment]
I am trying to deploy my ML model to azure container instance , I am following the same as below 

https://github.com/Azure/MachineLearningNotebooks/blob/master/how-to-use-azureml/deployment/deploy-multi-model/multi-model-register-and-deploy.ipynb


I am getting error as after deployment as below



Service deployment polling reached non-successful terminal state

==> WARNING: A newer version of conda exists. <==
  current version: 4.9.2
  latest version: 4.11.0

Please update conda by running

    $ conda update -n base -c defaults conda


Pip subprocess error:
ERROR: Could not find a version that satisfies the requirement azureml.api (from -r /azureml-environment-setup/condaenv.85634mmm.requirements.txt (line 8)) (from versions: none)
ERROR: No matching distribution found for azureml.api (from -r /azureml-environment-setup/condaenv.85634mmm.requirements.txt (line 8))

**Comment by madiepev** [comment]
@ArunP-AtreyaLabs please submit an issue to that repo instead of here. Issues submitted here should be related to the content in this repo. You may also want to check this repo: https://github.com/Azure/azureml-examples/blob/main/python-sdk/tutorials/deploy-local/1.deploy-local.ipynb as it is more up-to-date then the one you shared.
