### ISSUE TITLE
Failure when testing deployed web service

### ISSUE THREAD

**Issue by dabrock51** [MicrosoftLearning/mslearn-dp100#61]
Lab 02 - Use Automated Machine Learning

When testing the deployed web service as per written instructions under Test the deployed service, a 502 error is returned. All steps performed as written, the model itself works properly. Fails both using an Azure trial pass and a MSDN pay-as-you-go subscription in US East, US Central and US West

<img width="457" alt="image" src="https://user-images.githubusercontent.com/32367563/151714070-1b1b0668-93f3-4a36-a292-9be096edf84b.png">

**Comment by madiepev** [comment]
@dabrock51 Thank you for reporting this. I updated the code in the notebook, it should work now!
