### ISSUE TITLE
conda error - 

### ISSUE THREAD

**Issue by brian1985** [MicrosoftLearning/mslearn-dp100#69]
The following code fails at the last line
```

from azureml.core import Experiment, ScriptRunConfig, Environment
from azureml.widgets import RunDetails

# Create a Python environment for the experiment (from a .yml file)
env = Environment.from_conda_specification("experiment_env", "environment.yml")

# Create a script config
script_config = ScriptRunConfig(source_directory=experiment_folder,
                                script='diabetes_experiment.py',
                                environment=env)

# submit the experiment
experiment = Experiment(workspace=ws, name='mslearn-diabetes')
run = experiment.submit(config=script_config)
RunDetails(run).show()
run.wait_for_completion()
```

With the following error
[2022-03-31T14:28:17.918370] Using urllib.request Python 2
Streaming log file azureml-logs/60_control_log.txt Running: ['/bin/bash', '/tmp/azureml_runs/mslearn-diabetes_1648736896_939dbeab/azureml-environment-setup/conda_env_checker.sh']

Starting the daemon thread to refresh tokens in background for process with pid = 20097
Materialized conda environment not found on target: /home/azureuser/.azureml/envs/azureml_809a074975457de1dd27bdfcf2d79d61
[2022-03-31T14:28:18.029888] Logging experiment preparation status in history service.
Running: ['/bin/bash', '/tmp/azureml_runs/mslearn-diabetes_1648736896_939dbeab/azureml-environment-setup/conda_env_builder.sh']
Running: [u'conda', '--version']
[Errno 2] No such file or directory
()
Unable to run conda package manager. AzureML uses conda to provision python
environments from a dependency specification. To manage the python environment
manually instead, set userManagedDependencies to True in the python environment
configuration. To use system managed python environments, install conda from:
https://conda.io/miniconda.html
()
[2022-03-31T14:28:18.635517] Logging error in history service: Failed to run ['/bin/bash', '/tmp/azureml_runs/mslearn-diabetes_1648736896_939dbeab/azureml-environment-setup/conda_env_builder.sh'] 
 Exit code 1 
Details can be found in azureml-logs/60_control_log.txt log file.

Uploading control log...

Error occurred: Unable to run conda package manager. AzureML uses conda to provision python
environments from a dependency specification. To manage the python environment
manually instead, set userManagedDependencies to True in the python environment
configuration. To use system managed python environments, install conda from:
https://conda.io/miniconda.html

Using a personal azure account so I don't think it is permissions 
Compute instance is standard_D2_V3
Using jupyter notebook
Previous cells run fine.

Exercise is from this:
git clone https://github.com/MicrosoftLearning/mslearn-dp100 mslearn-dp100
Run Experiment section (skipped the others since I already had done those steps on a previous learning module)

**Comment by madiepev** [comment]
@brian1985 which notebook are you running? Are you running the notebooks from an Azure ML compute instance? What did you skip? Cells or notebooks?

**Comment by brian1985** [comment]
Looks like notebook 05 - Train Models is also doing it.

I opened a terminal in the AzureML > Notebook pane and ran:
which conda and get:
/anaconda/envs/azureml_py38/bin/conda

In my environment.yaml I updated it to:
`# Conda environment specification. The dependencies defined in this file will
# be automatically provisioned for runs with userManagedDependencies=False.

# Details about the Conda environment file format:
# https://conda.io/docs/user-guide/tasks/manage-environments.html#create-env-file-manually

name: simple_environment
dependencies:
  # The python interpreter version.
  # Currently Azure ML only supports 3.5.2 and later.
- python=3.8  <<<<< use to be 3.6.2 but also tried to set to 3.8 to match the Jupyter Runtime compute instance.
- scikit-learn
- pandas
- pip
- pip:
  - azureml-defaults
  - azureml-mlflow

`

`from azureml.core import Experiment, ScriptRunConfig, Environment
from azureml.widgets import RunDetails

# Create a Python environment for the experiment (from a .yml file)
env = Environment.from_conda_specification("experiment_env", "environment.yml")

# Create a script config
script_config = ScriptRunConfig(source_directory=training_folder,
                                script='diabetes_training.py',
                                environment=env) 

# submit the experiment run
experiment_name = 'mslearn-train-diabetes'
experiment = Experiment(workspace=ws, name=experiment_name)
run = experiment.submit(config=script_config)

# Show the running experiment run in the notebook widget
# RunDetails(run).show()

# Block until the experiment run has completed
# run.wait_for_completion()`

The above code fails. So I believe this time it is happening in the submit function.

**Comment by madiepev** [comment]
@brian1985 I wasn't able to reproduce the error. Everything runs fine for me. The experiment run works if you just do it inline right? So it's only when submitting the experiment that the error occurs? Could be something with the environment that is unsuccessful. Maybe try with Standard_DS11_v2 compute instance as described in the instructions? I wouldn't really suspect that to matter but may be good to rule some things out.

**Comment by madiepev** [comment]
<img width="661" alt="image" src="https://user-images.githubusercontent.com/48012580/161112355-b9b55c37-b161-4a82-858f-d2e4c16766cf.png">
Maybe also check whether you're using the right kernel? As shown in the screenshot?

**Comment by brian1985** [comment]
I'm using the kernel of Python 3.8 which might have to do with it. I don't see 3.6 in the list. How do get that one added?

**Comment by brian1985** [comment]
Tried the different compute environment and that didn't help. 

I also tried deleting my old ML Workspace and build a new one.

Here is what I get after selecting my compute resource inside Jupyter notebooks:
Jupyter kernel matching 'Python 3.6 - AzureML' (python3-azureml) was not found on compute instance 'NAME'

Looks like it is no longer a default compute option. Can you try on 3.8 and see if you can still get it to run?
Even with a complete rebuild, I can't get it to work.

Running notebook 05 - Train Models.ipynb

```
from azureml.core import Experiment, ScriptRunConfig, Environment
from azureml.widgets import RunDetails

# Create a Python environment for the experiment (from a .yml file)
env = Environment.from_conda_specification("experiment_env", "environment.yml")

# Create a script config
script_config = ScriptRunConfig(source_directory=training_folder,
                                script='diabetes_training.py',
                                environment=env) 

# submit the experiment run
experiment_name = 'mslearn-train-diabetes'
experiment = Experiment(workspace=ws, name=experiment_name)
run = experiment.submit(config=script_config)

# Show the running experiment run in the notebook widget
RunDetails(run).show()

# Block until the experiment run has completed
run.wait_for_completion()
```

```
WIDGET FAILED

[2022-03-31T22:05:44.042965] Using urllib.request Python 2
Streaming log file azureml-logs/60_control_log.txt
Starting the daemon thread to refresh tokens in background for process with pid = 21442
Running: ['/bin/bash', '/tmp/azureml_runs/mslearn-train-diabetes_1648764343_503ff49f/azureml-environment-setup/conda_env_checker.sh']
Materialized conda environment not found on target: /home/azureuser/.azureml/envs/azureml_809a074975457de1dd27bdfcf2d79d61
[2022-03-31T22:05:44.151103] Logging experiment preparation status in history service.
Running: ['/bin/bash', '/tmp/azureml_runs/mslearn-train-diabetes_1648764343_503ff49f/azureml-environment-setup/conda_env_builder.sh']
Running: [u'conda', '--version']
[Errno 2] No such file or directory
()
Unable to run conda package manager. AzureML uses conda to provision python
environments from a dependency specification. To manage the python environment
manually instead, set userManagedDependencies to True in the python environment
configuration. To use system managed python environments, install conda from:
https://conda.io/miniconda.html
()
[2022-03-31T22:05:44.394311] Logging error in history service: Failed to run ['/bin/bash', '/tmp/azureml_runs/mslearn-train-diabetes_1648764343_503ff49f/azureml-environment-setup/conda_env_builder.sh'] 
 Exit code 1 
Details can be found in azureml-logs/60_control_log.txt log file.

Uploading control log...

Error occurred: Unable to run conda package manager. AzureML uses conda to provision python
environments from a dependency specification. To manage the python environment
manually instead, set userManagedDependencies to True in the python environment
configuration. To use system managed python environments, install conda from:
https://conda.io/miniconda.html
```

**Comment by madiepev** [comment]
Wait so you said that the inline experiment also didn't work? Then it's likely not an issue of environment. I also could run the code with Python 3.8 - Azure ML.

What was the error message when you ran the cell as shown below?

```python
from azureml.core import Experiment
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline 

# Create an Azure ML experiment in your workspace
experiment = Experiment(workspace=ws, name="mslearn-diabetes")

# Start logging data from the experiment, obtaining a reference to the experiment run
run = experiment.start_logging()
print("Starting experiment:", experiment.name)

# load the data from a local file
data = pd.read_csv('data/diabetes.csv')

# Count the rows and log the result
row_count = (len(data))
run.log('observations', row_count)
print('Analyzing {} rows of data'.format(row_count))

# Plot and log the count of diabetic vs non-diabetic patients
diabetic_counts = data['Diabetic'].value_counts()
fig = plt.figure(figsize=(6,6))
ax = fig.gca()    
diabetic_counts.plot.bar(ax = ax) 
ax.set_title('Patients with Diabetes') 
ax.set_xlabel('Diagnosis') 
ax.set_ylabel('Patients')
plt.show()
run.log_image(name='label distribution', plot=fig)

# log distinct pregnancy counts
pregnancies = data.Pregnancies.unique()
run.log_list('pregnancy categories', pregnancies)

# Log summary statistics for numeric columns
med_columns = ['PlasmaGlucose', 'DiastolicBloodPressure', 'TricepsThickness', 'SerumInsulin', 'BMI']
summary_stats = data[med_columns].describe().to_dict()
for col in summary_stats:
    keys = list(summary_stats[col].keys())
    values = list(summary_stats[col].values())
    for index in range(len(keys)):
        run.log_row(col, stat=keys[index], value = values[index])
        
# Save a sample of the data and upload it to the experiment output
data.sample(100).to_csv('sample.csv', index=False, header=True)
run.upload_file(name='outputs/sample.csv', path_or_stream='./sample.csv')

# Complete the run
run.complete()
```

Essentially the question is, where do you get your first error and what is the message?

**Comment by madiepev** [comment]
does it fix the issue if you add the DockerConfiguration? 

```
from azureml.core import Experiment, ScriptRunConfig, Environment
from azureml.core.runconfig import DockerConfiguration
from azureml.widgets import RunDetails

# Create a Python environment for the experiment (from a .yml file)
experiment_env = Environment.from_conda_specification("experiment_env", "environment.yml")
# experiment_env.python.user_managed_dependencies=False 

# Create a script config
script_config = ScriptRunConfig(source_directory=experiment_folder,
                                script='diabetes_experiment.py',
                                environment=experiment_env,
                                docker_runtime_config=DockerConfiguration(use_docker=True))

# submit the experiment
experiment = Experiment(workspace=ws, name='mslearn-diabetes')
run = experiment.submit(config=script_config)
RunDetails(run).show()
run.wait_for_completion()
```

**Comment by brian1985** [comment]
so I can run the block of code you sent just fine.

I'll try the docker code. The first line of error is probably the one I sent above. In each notebook it always seems to happen on the line containing run.wait_for_completion() (or the one above regarding the RunDetails(run).show()

Error would be what is above.

**Comment by madiepev** [comment]
Ok. Let me know if the docker config fixes the issue. Remember to add the import as well as the parameter in the runconfig if you want to try it across different experiments.

**Comment by brian1985** [comment]
It looks like that docker code is working. It ran the script and is training a model.

**Comment by brian1985** [comment]
This similar code still does not:

from azureml.core import Experiment, ScriptRunConfig, Environment
from azureml.widgets import RunDetails

# Create a Python environment for the experiment (from a .yml file)
env = Environment.from_conda_specification("experiment_env", "environment.yml")

# Create a script config
script_config = ScriptRunConfig(source_directory=training_folder,
                                script='diabetes_training.py',
                                environment=env) 

# submit the experiment run
experiment_name = 'mslearn-train-diabetes'
experiment = Experiment(workspace=ws, name=experiment_name)
run = experiment.submit(config=script_config)

# Show the running experiment run in the notebook widget
RunDetails(run).show()

# Block until the experiment run has completed
run.wait_for_completion()



Error is similar as before (but not sure if exactly the same.):

[2022-04-01T13:31:43.772625] Using urllib.request Python 2
Streaming log file azureml-logs/60_control_log.txt
Starting the daemon thread to refresh tokens in background for process with pid = 25561
Running: ['/bin/bash', '/tmp/azureml_runs/mslearn-train-diabetes_1648819785_b37d40c7/azureml-environment-setup/conda_env_checker.sh']
Materialized conda environment not found on target: /home/azureuser/.azureml/envs/azureml_809a074975457de1dd27bdfcf2d79d61
[2022-04-01T13:31:43.887651] Logging experiment preparation status in history service.
Failed to set run status: Preparing
400
{
  "error": {
    "code": "UserError",
    "severity": null,
    "message": "Run with id mslearn-train-diabetes_1648819785_b37d40c7 is in a terminal state and cannot be updated.",
    "messageFormat": "Run with id {runId} is in a terminal state and cannot be updated.",
    "messageParameters": {
      "runId": "mslearn-train-diabetes_1648819785_b37d40c7"
    },
    "referenceCode": null,
    "detailsUri": null,
    "target": null,
    "details": [],
    "innerError": {
      "code": "BadArgument",
      "innerError": {
        "code": "TerminalRunState",
        "innerError": null
      }
    },
    "debugInfo": null,
    "additionalInfo": null
  },
  "correlation": {
    "operation": "318a5e6d82e6467dc3933e91d005ddd4",
    "request": "38165fd6b86df70c"
  },
  "environment": "eastus",
  "location": "eastus",
  "time": "2022-04-01T13:31:44.1940244+00:00",
  "componentName": "run-history"
}
Running: ['/bin/bash', '/tmp/azureml_runs/mslearn-train-diabetes_1648819785_b37d40c7/azureml-environment-setup/conda_env_builder.sh']
Running: [u'conda', '--version']
[Errno 2] No such file or directory
()
Unable to run conda package manager. AzureML uses conda to provision python
environments from a dependency specification. To manage the python environment
manually instead, set userManagedDependencies to True in the python environment
configuration. To use system managed python environments, install conda from:
https://conda.io/miniconda.html
()
[2022-04-01T13:31:44.370096] Logging error in history service: Failed to run ['/bin/bash', '/tmp/azureml_runs/mslearn-train-diabetes_1648819785_b37d40c7/azureml-environment-setup/conda_env_builder.sh'] 
 Exit code 1 
Details can be found in azureml-logs/60_control_log.txt log file.

Uploading control log...

Error occurred: Service invocation timed out. 
Request: POST https://eastus.api.azureml.ms/environment/v1.0/subscriptions/102be847-967b-4249-bcba-78acb344e3f6/resourceGroups/ml/providers/Microsoft.MachineLearningServices/workspaces/bch-ml-resources/environments/experiment_env/versions/Autosave_2022-03-31T22:04:04Z_171a49d9/recipe 
 Message: Operation canceled Time waited: 00:00:10.0015708

**Comment by brian1985** [comment]
And if I comment out these two lines it does work.

# Show the running experiment run in the notebook widget
#RunDetails(run).show()

# Block until the experiment run has completed
#run.wait_for_completion()

**Comment by madiepev** [comment]
Right but if you add the docker configuration like below?

```
from azureml.core import Experiment, ScriptRunConfig, Environment
from azureml.core.runconfig import DockerConfiguration
from azureml.widgets import RunDetails

# Create a Python environment for the experiment (from a .yml file)
env = Environment.from_conda_specification("experiment_env", "environment.yml")

# Create a script config
script_config = ScriptRunConfig(source_directory=training_folder,
                                script='diabetes_training.py',
                                environment=env,
                                docker_runtime_config=DockerConfiguration(use_docker=True)) 

# submit the experiment run
experiment_name = 'mslearn-train-diabetes'
experiment = Experiment(workspace=ws, name=experiment_name)
run = experiment.submit(config=script_config)

# Show the running experiment run in the notebook widget
RunDetails(run).show()

# Block until the experiment run has completed
run.wait_for_completion()
```

**Comment by brian1985** [comment]
that worked

**Comment by madiepev** [comment]
it worked including the RunDetails and run.wait_for_completion?

**Comment by brian1985** [comment]
yes. The entire cell ran just fine with the docker config.

**Comment by madiepev** [comment]
great! I'll add those lines to the configs for notebooks 4 and 5 and close this issue. You can create a new issue if you encounter any errors still.

**Comment by brian1985** [comment]
This change needs to happen in workbook 06 as well towards the middle (under run model using a dataset.
