### ISSUE TITLE
Suggestion - Add - Install the Azure Machine Learning SDK

### ISSUE THREAD

**Issue by flegaspi700** [MicrosoftLearning/mslearn-dp100#7]
Add:
Install the Azure Machine Learning SDK
The Azure Machine Learning SDK is updated frequently. Run the following cell to upgrade to the latest release, along with the additional package to support notebook widgets.

In [ ]: !pip install --upgrade azureml-sdk azureml-widgets

To: https://github.com/MicrosoftLearning/mslearn-dp100/blob/main/04%20-%20Run%20Experiments.ipynb

Reason:  
- 02-Experiments is the first step-by-step exercise in this module. 
- Most of the subsequent exercises has this step.

**Comment by GraemeMalcolm** [comment]
This is by design. We know that the version installed in the 02 lab will work, and we don't want to cover installation yet
