### ISSUE TITLE
Only specific Python versions are supported

### ISSUE THREAD

**Issue by marcindulak** [MicrosoftLearning/mslearn-dp100#72]
https://github.com/MicrosoftLearning/mslearn-dp100/blob/8601551af6c32a4c75fd9ecffce750583c2ab4b8/environment.yml#L10

This issue tracks Python support in azureml https://github.com/Azure/MachineLearningNotebooks/issues/1326

**Comment by madiepev** [comment]
Closing for now. Let us know if there's something that needs to be fixed

**Comment by marcindulak** [comment]
Users evaluating azureml will find useful information about the supported Python releases. Ideally environment.yaml would contain the latest release of Python that is known to work for the notebooks in the repo.
environment.yml uses an older, unsupported Python 3.6.2. Python 3.6 is end-of-life and the latest release of 3.6 was https://www.python.org/downloads/release/python-3615/.
