### ISSUE TITLE
Fairlearn dashboard does not name disparity charts

### ISSUE THREAD

**Issue by marcindulak** [MicrosoftLearning/mslearn-dp100#73]
The [Train a model](https://github.com/MicrosoftLearning/mslearn-dp100/blob/8601551af6c32a4c75fd9ecffce750583c2ab4b8/15%20-%20Detect%20Unfairness.ipynb) section contains the following explanation

> View the dashboard visualization, which shows:
> - Disparity in performance - how the selected performance metric compares for the subpopulations, including underprediction (false negatives) and overprediction (false positives).
> - Disparity in predictions - A comparison of the number of positive cases per subpopulation.

The "Age | Recall | Demographic parity difference" dashboard looks with fairlearn 0.7.0 like the one below

![Screenshot from 2022-04-03 16-58-15](https://user-images.githubusercontent.com/3178318/161434404-255721e6-d495-45e7-adb2-fbe8d9b9c737.png)

The fairlearn documentation up to and including version 0.6.2 contained a section [Fairlearn dashboard](https://fairlearn.org/v0.6.2/user_guide/assessment.html#fairlearn-dashboard) which used the concept of disparities, however fairlearn 0.7.0 does not have that section.

**Comment by madiepev** [comment]
Fixed to reflect new UI

**Comment by marcindulak** [comment]
It looks like this commit https://github.com/MicrosoftLearning/mslearn-dp100/commit/c7cd2ef213fa678cd7fb29b3564d8daec27e4268 updated the description to match the currently produced graphs.
