### ISSUE TITLE
Lab 13 Explore Differential Privacy

### ISSUE THREAD

**Issue by rdoelkers** [MicrosoftLearning/mslearn-dp100#74]
Hello:

Since we are not being able to run the pip install commands and add the required tools, example: 

**pip install opendp-smartnoise==0.1.4.2**

We get a message of pip command not found. 

**Next cell after setting up adata fails in order to execute since package is missing:**

import opendp.smartnoise.core as sn

cols = list(diabetes.columns)
age_range = [0.0, 120.0]
samples = len(diabetes)

with sn.Analysis() as analysis:
    # load data
    data = sn.Dataset(path=data_path, column_names=cols)
    
    # Convert Age to float
    age_dt = sn.to_float(data['Age'])
    
    # get mean of age
    age_mean = sn.dp_mean(data = age_dt,
                          privacy_usage = {'epsilon': .50},
                          data_lower = age_range[0],
                          data_upper = age_range[1],
                          data_rows = samples
                         )
    
analysis.release()

# print differentially private estimate of mean age
print("Private mean age:",age_mean.value)

# print actual mean age
print("Actual mean age:",diabetes.Age.mean())

**Comment by GraemeMalcolm** [comment]
When did you pull the notebooks? (they were all updated yesterday to address the Python version issues)

**Comment by rdoelkers** [comment]
It was earlier today. During the early morning. We found a workaround, indtalling the packages using the terminal.

**Comment by GraemeMalcolm** [comment]
Are you using a new workspace / compute instance? Or one that was created previously?

**Comment by GraemeMalcolm** [comment]
I just tested successfully in a new workspace. If you created your workspace and compute prior to yesterday, create new ones - Azure ML was updated and the default Python kernel is not 3.8, and pip can be run like a native command in Jupyter.
