### ISSUE TITLE
Error in 06-Work With Data

### ISSUE THREAD

**Issue by Blubbaa** [MicrosoftLearning/mslearn-dp100#76]
I am getting a deprecation error in the notebook "06-Work With Data":

```Python3
default_ds.upload_files(files=['./data/diabetes.csv', './data/diabetes2.csv'], # Upload the diabetes csv files in /data
                       target_path='diabetes-data/', # Put it in a folder path in the datastore
                       overwrite=True, # Replace existing files of the same name
                       show_progress=True)
```

> "datastore.upload_files" is deprecated after version 1.0.69. Please use "FileDatasetFactory.upload_directory" instead. See Dataset API change notice at [https://aka.ms/dataset-deprecation]().

**Comment by madiepev** [comment]
@Blubbaa thanks for addressing this. We fixed the issue.
