### ISSUE TITLE
Lab 08 - Create a Pipeline - Docker pull authentication error inside PythonScriptStep

### ISSUE THREAD

**Issue by dmesquita** [MicrosoftLearning/mslearn-dp100#77]
Hi everyone!
I'm running the lab and when I try to run the pipeline it says this in the first PythonScriptStep:

> AzureMLCompute job failed.
FailedPullingImage: Unable to pull docker image
	imageName: [...]
	error: Run docker command to pull public image failed with error: Error response from daemon: Head https://[...]: unauthorized: authentication required, visit https://aka.ms/acr/authorization for more information.

I think I need to authenticate but I don't know how, I've tried to do it using the DockerConfiguration() of the RunConfiguration() but the arguments are for the Docker run command only.

What should I do? I've managed to login and perform the docker pull comand using the terminal of the computer instance.
Thanks!

**Comment by madiepev** [comment]
@dmesquita could you try to restart your compute? If it still doesn't work, I'd suggest to report a bug in the Studio. Closing the issue for now as it's not an issue in the content.

**Comment by dmesquita** [comment]
In case someone ends up here, for it to work we need to use a Compute Cluster with the System assigned identity activated
