### ISSUE TITLE
Lab 3A: Widget is not loaded

### ISSUE THREAD

**Issue by instrovatesimran1** [MicrosoftLearning/mslearn-dp100#78]
when using the code:
from azureml.widgets import RunDetails
   RunDetails(run).show()

The widgets are not getting loaded.

**Comment by madiepev** [comment]
@instrovatesimran1 where are you running the notebook? Is it in the Azure Machine Learning Studio?

**Comment by instrovatesimran1** [comment]
Yes

**Comment by madiepev** [comment]
@instrovatesimran1 I'm not able to reproduce your error. It may be a bug in the Studio. Please use the feedback/support option in the Studio to report the bug. I'll close the issue for now.
