### ISSUE TITLE
Dataset check in Labs 6-8 references wrong folder

### ISSUE THREAD

**Issue by sanpietro** [MicrosoftLearning/mslearn-dp100#79]
`from azureml.core import Dataset
from azureml.data.datapath import DataPath

default_ds = ws.get_default_datastore()

if 'diabetes dataset' not in ws.datasets:
    Dataset.File.upload_directory(src_dir='data',
                              target=DataPath(default_ds, 'diabetes-data-new/')------>Change this to diabetes-data to match changes made to Lab 6
                              )

    #Create a tabular dataset from the path on the datastore (this may take a short while)
    tab_data_set = Dataset.Tabular.from_delimited_files(path=(default_ds, 'diabetes-data/*.csv'))
`

**Comment by madiepev** [comment]
@sanpietro thank you! should be fixed now
