### ISSUE TITLE
ImportError: cannot import name 'AzureMLAggregatedException'

### ISSUE THREAD

**Issue by pgari** [MicrosoftLearning/mslearn-dp100#8]
I get `ImportError: cannot import name 'AzureMLAggregatedException'` in `06 - Work with Data.ipynb` on Step 12 when running the script as an experiment. 

![image](https://user-images.githubusercontent.com/7280250/104260534-b783b380-54a9-11eb-800c-633ad014491d.png)

**Comment by MarkTension** [comment]
Seems like some breaking changes in the latest version of azure-widgets. Until they fix it you can use the previous version by running 

`!pip install azureml-widgets==1.19.0`

**Comment by D2theMC** [comment]
You need to restart the kernel. Either restart the instance or through the Jupyter notebook and run through again.

**Comment by GraemeMalcolm** [comment]
Thanks for sharing the workarounds. I'm unable to repro this on a clean Compute Instance.

**Comment by GraemeMalcolm** [comment]
AH! So this happens if you haven't completed previous exercises (where you install the widgets package in a terminal), which is why I couldn't repro it. If you upgrade the widgets package in the notebook itself, it doesn't load properly until you restart the kernel.

Working on a fix...

**Comment by GraemeMalcolm** [comment]
OK. I've added a step to install the packages immediately after cloning the repo. I've also added a note to restart the kernel if you opt to install the package in the notebook.
