### ISSUE TITLE
Notebook 17 - Datastore method upload_files deprecated

### ISSUE THREAD

**Issue by arthurangelici** [MicrosoftLearning/mslearn-dp100#80]
I just splitted the files in data and target folders and updated the method in each session
Baseline:
Dataset.File.upload_directory(src_dir='data',
                              target=DataPath(default_ds, 'diabetes-baseline/')
                              )

Target:
Dataset.File.upload_directory(src_dir='target',
                              target=DataPath(default_ds, path_on_datastore)
                              )

However, in outputs/logs I keep getting the deprecated warning ["datastore.upload_files" is deprecated after version 1.0.69. Please use "FileDatasetFactory.upload_directory" instead. See Dataset API change notice at https://aka.ms/dataset-deprecation]. 
I noticed that in the code generated in the job there is indeed the upload_files function in the Class MetricProcessor.
As the job completed, I was able to generate the json metrics and values, but I can't see them in the monitor panel. The first request returns the datadrift object info and the id of the metrics. But the next request with the id and operationType=LastestData returns empty

**Comment by madiepev** [comment]
@arthurangelici thanks for reporting it. It should be fixed now!
