### ISSUE TITLE
Explore and analyze data with Python - Writing errors

### ISSUE THREAD

**Issue by AD-HO** [MicrosoftLearning/mslearn-dp100#87]
Dear MS Learn Team,
I would like to highlight the following  two errors I faced when I was studying the "Explore and analyze data with Python" Module : 

-- Unit 5 : Exercise - Visualize data with Matplotlib : in the Summary, at the 6th point (see Figure 1) . Its written " Estimated what the population of **graphse** might look like from a sample of grades." where it should be "Estimated what the population of **graphs** might look like from a sample of grades" .

-- Unit  7 : Exercise - Examine real world data :  in the SandBox , at the 15th coding cell  which starts with "from scipy import stats (see Figure 2) . It's written in the fifth comment "# Create a scatter plot of Grade vs **Salary**" where it should be "# Create a scatter plot of Grade vs **StudyHours**"

-- Figure 1 --
<img width="545" alt="S1" src="https://user-images.githubusercontent.com/59181393/176541278-c1c20176-55c3-44bd-972d-9b101d681c2c.png">

-- Figure 2 --
<img width="580" alt="S2" src="https://user-images.githubusercontent.com/59181393/176541364-82d357b7-8b31-4b76-a31f-fbe849f549d9.png">

**Comment by GraemeMalcolm** [comment]
This lab isn't from this repo, and isnlt managed by this team. Please report the issues in the Microsoft Learn module where you enountered them
