### ISSUE TITLE
Error Loading Notebooks

### ISSUE THREAD

**Issue by tonyksong** [MicrosoftLearning/mslearn-dp100#9]
When I try to load a lab notebook in VS Code, the page is blank. When I try to load the same lab notebook in Jupyter Notebooks via Anaconda, I get an error message:

Error Loading Notebook
"Unreadable Notebook: C:\Users\pusongan\Azure-Training\mslearn-dp100\08 - Create a Pipeline.ipynb NotJSONError("Notebook does not appear to be JSON: '\\n\\n\\n\\n\\n\\n<!DOCTYPE html>\\n<html lang...")"

<img width="791" alt="Screenshot 2021-01-19 090630" src="https://user-images.githubusercontent.com/38965603/105045251-b74d6000-5a35-11eb-9f2f-0000aef151c1.png">
<img width="959" alt="Screenshot 2021-01-19 090826" src="https://user-images.githubusercontent.com/38965603/105045451-ebc11c00-5a35-11eb-9aca-94209db0020f.png">

**Comment by GraemeMalcolm** [comment]
Looks like an incomplete download - try recloning the repo
