### ISSUE TITLE
Error when testing published endpoint with designer prediction

### ISSUE THREAD

**Issue by dtarek1** [MicrosoftLearning/mslearn-dp100#98]
In Module 2 :Use Azure Machine Learning Designer

Step:
Test the web service

The file Get Designer prediction contains a wrong input name. 

Original file : 
**data = {
    "Inputs": {
        "WebServiceInput0":
        [
            {
                    'PatientID': 1882185,
                    'Pregnancies': 9,
                    'PlasmaGlucose': 104,
                    'DiastolicBloodPressure': 51,
                    'TricepsThickness': 7,
                    'SerumInsulin': 24,
                    'BMI': 27.36983156,
                    'DiabetesPedigree': 1.3504720469999998,
                    'Age': 43,
            },
        ],
    },
    "GlobalParameters":  {
    }
}**

It gave an error because of "WebServiceInput0"

It should be : "input1"
data = {
    "Inputs": {
        "input1":
        [
            {
                    'PatientID': 1882185,
                    'Pregnancies': 9,
                    'PlasmaGlucose': 104,
                    'DiastolicBloodPressure': 51,
                    'TricepsThickness': 7,
                    'SerumInsulin': 24,
                    'BMI': 27.36983156,
                    'DiabetesPedigree': 1.3504720469999998,
                    'Age': 43,
            },
        ],
    },
    "GlobalParameters":  {
    }
}

**Comment by madiepev** [comment]
Issue has been resolved. Thank you for your feedback.
