### ISSUE TITLE
Minor referencing error in Lab 07 Work with compute

### ISSUE THREAD

**Issue by VEshelbyMTT** [MicrosoftLearning/mslearn-dp100#99]
Very low priority: variable name in notebook referenced as 'Experiment_env' but references as 'diabetes-experiment-env' in explanation. 

![image](https://user-images.githubusercontent.com/104829457/207317587-5191ef7c-8512-4b4a-8557-82760f8ba805.png)

![image](https://user-images.githubusercontent.com/104829457/207317613-9bfffb1f-48f6-487a-98c3-16f68ee81d37.png)

![image](https://user-images.githubusercontent.com/104829457/207317637-7b6a3859-cceb-4c50-85de-ac84c9ec235a.png)

(actual text so you can cntl + f it):
`Note that the environment is registered with the name you assigned when you first created it (in this case, diabetes-experiment-env).`

Location: 07 Work with Compute
https://github.com/MicrosoftLearning/mslearn-dp100/blob/main/07%20-%20Work%20with%20Compute.ipynb

**Comment by madiepev** [comment]
Fixed the issue. Thanks!
